version: '3.3'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/vhost:/etc/nginx/vhost.d
      - nginx_dhparam:/etc/nginx/dhparam
      - nginx_html:/usr/share/nginx/html
      - nginx_certs:/etc/nginx/certs:ro
      #- /run/user/1000/docker.sock:/tmp/docker.sock:ro # rootless mode
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-letsencrypt
    restart: unless-stopped
    depends_on:
      - "nginx-proxy"
    volumes:
      #- /run/user/1000/docker.sock:/var/run/docker.sock:ro # rootless mode
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx_acme:/etc/acme.sh
      - ./nginx/vhost:/etc/nginx/vhost.d
      - nginx_html:/usr/share/nginx/html
      - nginx_dhparam:/etc/nginx/dhparam
      - nginx_certs:/etc/nginx/certs
    environment:
       - DEFAULT_EMAIL=cesarsanz91@gmail.com

  api:
    build: ./api
    restart: unless-stopped
    expose:
      - "8000"
    volumes:
      - ./api/logs:/app/logs
      - ./api/data:/app/data
    environment:
      - VIRTUAL_HOST=api.calc.cesarsanz.dev
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=api.calc.cesarsanz.dev

volumes:
  nginx_acme:
  nginx_vhost:
  nginx_dhparam:
  nginx_html:
  nginx_certs: